// SPOT ON! question pool.
// Each entry: a single-word answer (3-12 letters, A-Z) and its clue.
// Add as many as you like — the daily picks 15 by date-seed, cycling the
// whole pool before any answer repeats. More questions = longer runway.
// Current pool: 213 questions  ->  ~14 days before any repeat.

export const QUESTION_POOL = [
  { a: "MARS", q: "Which planet is known as the Red Planet?" },
  { a: "OXYGEN", q: "Which gas do humans need to breathe to survive?" },
  { a: "GRAVITY", q: "What force pulls objects toward the Earth?" },
  { a: "VOLCANO", q: "What is a mountain that can erupt with lava called?" },
  { a: "SKELETON", q: "What is the frame of bones inside your body called?" },
  { a: "DIAMOND", q: "Which gemstone is the hardest natural material?" },
  { a: "MAGNET", q: "What attracts iron and has a north and south pole?" },
  { a: "RAINBOW", q: "What colourful arc appears in the sky after rain?" },
  { a: "PLANET", q: "What do we call a large body orbiting the Sun?" },
  { a: "COMET", q: "What icy space object grows a tail near the Sun?" },
  { a: "ECLIPSE", q: "What is it called when the Moon blocks the Sun?" },
  { a: "GLACIER", q: "What is a slow-moving river of ice called?" },
  { a: "HELIUM", q: "Which light gas makes party balloons float?" },
  { a: "FOSSIL", q: "What are the preserved remains of ancient life called?" },
  { a: "PENGUIN", q: "Which flightless bird lives mainly in Antarctica?" },
  { a: "DOLPHIN", q: "Which intelligent marine mammal lives in pods?" },
  { a: "OCTOPUS", q: "Which sea creature has eight arms and can change colour?" },
  { a: "CHEETAH", q: "Which big cat is the fastest land animal?" },
  { a: "GORILLA", q: "What is the largest living primate?" },
  { a: "KANGAROO", q: "Which animal carries its baby in a pouch and hops?" },
  { a: "ELEPHANT", q: "Which land animal is the largest and has a trunk?" },
  { a: "GIRAFFE", q: "Which animal is the tallest in the world?" },
  { a: "SPIDER", q: "Which eight-legged creature spins webs?" },
  { a: "EAGLE", q: "Which bird of prey is a national symbol of the USA?" },
  { a: "SALMON", q: "Which fish swims upstream to lay its eggs?" },
  { a: "TIGER", q: "Which big cat has orange fur with black stripes?" },
  { a: "EGYPT", q: "Which country is home to the Great Pyramids of Giza?" },
  { a: "JAPAN", q: "Which country is known as the Land of the Rising Sun?" },
  { a: "BRAZIL", q: "Which country is home to most of the Amazon rainforest?" },
  { a: "CANADA", q: "Which country has a red maple leaf on its flag?" },
  { a: "FRANCE", q: "Which country is home to the Eiffel Tower?" },
  { a: "ITALY", q: "Which boot-shaped country is home to Rome?" },
  { a: "KENYA", q: "Which African country is famous for safari and marathon runners?" },
  { a: "ICELAND", q: "Which island nation is famous for volcanoes and geysers?" },
  { a: "MEXICO", q: "Which country is the origin of tacos and the Aztecs?" },
  { a: "GREECE", q: "Which country is the birthplace of the Olympic Games?" },
  { a: "LONDON", q: "What is the capital of England?" },
  { a: "PARIS", q: "What is the capital of France?" },
  { a: "TOKYO", q: "What is the capital of Japan?" },
  { a: "CAIRO", q: "What is the capital of Egypt?" },
  { a: "SAHARA", q: "What is the largest hot desert in the world?" },
  { a: "EVEREST", q: "What is the tallest mountain on Earth?" },
  { a: "AMAZON", q: "What is the largest rainforest in the world?" },
  { a: "PACIFIC", q: "What is the largest ocean on Earth?" },
  { a: "NILE", q: "What is the longest river in Africa?" },
  { a: "ASIA", q: "What is the largest continent by land area?" },
  { a: "HEART", q: "Which organ pumps blood around your body?" },
  { a: "BRAIN", q: "Which organ controls your thoughts and movement?" },
  { a: "LUNGS", q: "Which pair of organs let you breathe?" },
  { a: "KIDNEY", q: "Which organ filters waste from your blood?" },
  { a: "MUSCLE", q: "What tissue contracts to move your body?" },
  { a: "SPINE", q: "What is the column of bones down your back called?" },
  { a: "NECTAR", q: "What sweet liquid do bees collect from flowers?" },
  { a: "POLLEN", q: "What powder do bees carry between flowers?" },
  { a: "ACORN", q: "What is the seed of an oak tree called?" },
  { a: "CACTUS", q: "Which spiky plant thrives in the desert?" },
  { a: "HONEY", q: "What sweet food do bees make?" },
  { a: "CHEESE", q: "What dairy food is made from curdled milk?" },
  { a: "BANANA", q: "Which long yellow fruit grows in bunches?" },
  { a: "AVOCADO", q: "Which green fruit is the key ingredient in guacamole?" },
  { a: "PASTA", q: "What Italian staple includes spaghetti and penne?" },
  { a: "PEPPER", q: "What spice is often paired with salt?" },
  { a: "MANGO", q: "Which tropical fruit has a large flat stone inside?" },
  { a: "GARLIC", q: "Which strong-smelling bulb is used to flavour cooking?" },
  { a: "PRETZEL", q: "Which knotted baked snack is often salted?" },
  { a: "WALNUT", q: "Which brain-shaped nut grows in a hard shell?" },
  { a: "GUITAR", q: "Which six-stringed instrument is used in rock and folk?" },
  { a: "PIANO", q: "Which instrument has black and white keys?" },
  { a: "VIOLIN", q: "Which string instrument is played with a bow?" },
  { a: "CAMERA", q: "What device captures photographs?" },
  { a: "COMPASS", q: "What instrument always points north?" },
  { a: "ANCHOR", q: "What heavy object stops a ship from drifting?" },
  { a: "CASTLE", q: "What fortified building did medieval kings live in?" },
  { a: "BRIDGE", q: "What structure carries a road across a river?" },
  { a: "ROCKET", q: "What vehicle launches astronauts into space?" },
  { a: "ENGINE", q: "What part of a car converts fuel into motion?" },
  { a: "PUZZLE", q: "What do you call a jigsaw you piece together?" },
  { a: "CANDLE", q: "What wax object gives light with a flame?" },
  { a: "UMBRELLA", q: "What do you hold over your head in the rain?" },
  { a: "BALLOON", q: "What rubber object floats when filled with helium?" },
  { a: "LANTERN", q: "What portable case holds a light or candle?" },
  // --- batch 2: pop culture, sport, entertainment + general ---
  { a: "BATMAN", q: "Which caped superhero protects Gotham City?" },
  { a: "GOTHAM", q: "Which fictional city does Batman protect?" },
  { a: "HOGWARTS", q: "What is the school of witchcraft in Harry Potter?" },
  { a: "NARNIA", q: "Which magical land is reached through a wardrobe?" },
  { a: "HOBBIT", q: "What kind of creature is Bilbo Baggins?" },
  { a: "BEATLES", q: "Which band from Liverpool included Lennon and McCartney?" },
  { a: "ELVIS", q: "Who was known as the King of Rock and Roll?" },
  { a: "MADONNA", q: "Which singer is known as the Queen of Pop?" },
  { a: "REGGAE", q: "Which music genre originated in Jamaica?" },
  { a: "OSCAR", q: "What is the famous golden Academy Award statuette called?" },
  { a: "GRAMMY", q: "Which award honours achievement in the music industry?" },
  { a: "TITANIC", q: "Which 1997 film featured a doomed ocean liner?" },
  { a: "AVATAR", q: "Which James Cameron film features blue-skinned Na'vi?" },
  { a: "ZOMBIE", q: "What undead creature shuffles through horror films?" },
  { a: "VAMPIRE", q: "What blood-drinking creature is Dracula?" },
  { a: "DRACULA", q: "Which famous count is the most well-known vampire?" },
  { a: "MUPPETS", q: "What is the name of Kermit and Miss Piggy's gang?" },
  { a: "KERMIT", q: "Which green frog leads the Muppets?" },
  { a: "PIKACHU", q: "Which yellow electric creature is the Pokemon mascot?" },
  { a: "MARIO", q: "Which moustachioed Nintendo plumber rescues a princess?" },
  { a: "TETRIS", q: "Which classic game involves arranging falling blocks?" },
  { a: "ARCADE", q: "What is a venue full of coin-operated games called?" },
  { a: "CARTOON", q: "What is an animated drawing for film or TV called?" },
  { a: "WIZARD", q: "What is Gandalf, and what does Oz famously have one of?" },
  { a: "JUKEBOX", q: "Which machine plays a song when you insert a coin?" },
  { a: "SEQUEL", q: "What is a film that continues an earlier story called?" },
  { a: "VINYL", q: "On what format are records pressed for turntables?" },
  { a: "KARAOKE", q: "What activity has you singing along to backing tracks?" },
  { a: "SOCCER", q: "What is the world's most popular sport, played with a round ball?" },
  { a: "CRICKET", q: "Which bat-and-ball sport features the Ashes series?" },
  { a: "TENNIS", q: "Which racquet sport is played at Wimbledon?" },
  { a: "WIMBLEDON", q: "Which London tournament is tennis's oldest Grand Slam?" },
  { a: "MARATHON", q: "What is the name of the 42-kilometre running race?" },
  { a: "OLYMPICS", q: "Which global sporting event is held every four years?" },
  { a: "REFEREE", q: "Who is the official that enforces the rules in a match?" },
  { a: "STADIUM", q: "What is a large arena where sport is played called?" },
  { a: "HOCKEY", q: "Which sport is played with sticks and a puck or ball?" },
  { a: "BOXING", q: "Which combat sport is fought with gloves in a ring?" },
  { a: "GOLF", q: "Which sport uses clubs to hit a ball into holes?" },
  { a: "BIRDIE", q: "In golf, what is a score of one under par called?" },
  { a: "PENALTY", q: "What is a free shot awarded for a foul called?" },
  { a: "OFFSIDE", q: "Which infringement involves being too far forward in football?" },
  { a: "WICKET", q: "What are the three stumps in cricket collectively called?" },
  { a: "TROPHY", q: "What is the prize lifted by a winning team called?" },
  { a: "MEDAL", q: "What is awarded to the top three Olympic finishers?" },
  { a: "SPRINT", q: "What is a short, all-out running race called?" },
  { a: "HURDLE", q: "What barrier do runners leap over on the track?" },
  { a: "SURFING", q: "Which sport involves riding ocean waves on a board?" },
  { a: "RUGBY", q: "Which sport features scrums and an oval ball?" },
  { a: "ASHES", q: "Which cricket series is contested by Australia and England?" },
  { a: "UMPIRE", q: "Who officiates a game of cricket or tennis?" },
  { a: "NETBALL", q: "Which seven-a-side court sport is popular in Australia?" },
  { a: "SATURN", q: "Which planet is famous for its system of rings?" },
  { a: "NEPTUNE", q: "Which blue ice giant is the farthest planet from the Sun?" },
  { a: "EINSTEIN", q: "Which physicist developed the theory of relativity?" },
  { a: "NEWTON", q: "Which scientist described gravity after seeing an apple fall?" },
  { a: "EDISON", q: "Which inventor is credited with the light bulb?" },
  { a: "PYRAMID", q: "What shape are the ancient Egyptian tombs at Giza?" },
  { a: "SPHINX", q: "Which Giza monument has a lion's body and a human head?" },
  { a: "KOALA", q: "Which Australian marsupial sleeps in eucalyptus trees?" },
  { a: "WOMBAT", q: "Which burrowing Australian marsupial has cube-shaped droppings?" },
  { a: "DINGO", q: "What is Australia's wild native dog called?" },
  { a: "PLATYPUS", q: "Which egg-laying mammal has a duck-like bill?" },
  { a: "OUTBACK", q: "What is the remote interior of Australia called?" },
  { a: "SYDNEY", q: "Which Australian city is famous for its Opera House?" },
  { a: "DESERT", q: "What is a dry, sandy region with little rainfall called?" },
  { a: "ICEBERG", q: "What floating chunk of ice sank the Titanic?" },
  { a: "TORNADO", q: "What is a violently spinning column of air called?" },
  { a: "THUNDER", q: "What sound follows a flash of lightning?" },
  { a: "OCTAGON", q: "What eight-sided shape shares its name with a UFC ring?" },
  { a: "TRIANGLE", q: "What three-sided shape is also a percussion instrument?" },
  // --- batch 3: pop culture, wordplay, trivia variety ---
  { a: "SHREK", q: "Which green ogre lives in a swamp with a talking donkey?" },
  { a: "SIMBA", q: "Which lion cub is the hero of The Lion King?" },
  { a: "WOODY", q: "Which cowboy doll leads the toys in Toy Story?" },
  { a: "FROZEN", q: "Which Disney film features the song 'Let It Go'?" },
  { a: "MATRIX", q: "In which film does Neo choose the red pill?" },
  { a: "JAWS", q: "Which film made everyone afraid of the water in 1975?" },
  { a: "ROCKY", q: "Which boxing film features a Philadelphia underdog?" },
  { a: "GANDALF", q: "Which wizard guides the Fellowship of the Ring?" },
  { a: "YODA", q: "Which small green Jedi master trains Luke Skywalker?" },
  { a: "VADER", q: "Which armoured villain is Luke Skywalker's father?" },
  { a: "HOMER", q: "Who is the bumbling dad of the Simpsons family?" },
  { a: "SCOOBY", q: "Which Great Dane solves mysteries with the gang?" },
  { a: "GARFIELD", q: "Which lazy orange cartoon cat loves lasagne?" },
  { a: "SNOOPY", q: "Which beagle belongs to Charlie Brown?" },
  { a: "BAMBI", q: "Which Disney deer's name became a film classic?" },
  { a: "ALADDIN", q: "Which Disney hero finds a genie in a lamp?" },
  { a: "GRINCH", q: "Which green character tried to steal Christmas?" },
  { a: "WONKA", q: "Which character owns a famous chocolate factory?" },
  { a: "HULK", q: "Which Marvel hero turns big and green when angry?" },
  { a: "THANOS", q: "Which purple villain collects the Infinity Stones?" },
  { a: "JOKER", q: "Which clown-faced villain is Batman's archenemy?" },
  { a: "RAMBO", q: "Which action hero shares his name with a 1982 film?" },
  { a: "BOND", q: "Which secret agent's code number is 007?" },
  { a: "DOROTHY", q: "Who follows the yellow brick road in Oz?" },
  { a: "NEMO", q: "Which clownfish gets lost in a Pixar film?" },
  { a: "ABBA", q: "Which Swedish pop group sang 'Dancing Queen'?" },
  { a: "QUEEN", q: "Which band recorded 'Bohemian Rhapsody'?" },
  { a: "DRUMS", q: "Which instrument keeps the beat in a rock band?" },
  { a: "CHOIR", q: "What is a group of singers performing together called?" },
  { a: "OPERA", q: "What dramatic musical art form is sung throughout?" },
  { a: "TRUMPET", q: "Which brass instrument is played by pressing valves?" },
  { a: "UKULELE", q: "Which small four-stringed Hawaiian instrument is like a tiny guitar?" },
  { a: "ENCORE", q: "What is an extra performance after applause called?" },
  { a: "LYRICS", q: "What are the words of a song called?" },
  { a: "TANGO", q: "Which dramatic ballroom dance comes from Argentina?" },
  { a: "PALINDROME", q: "What is a word that reads the same backwards, like 'kayak'?" },
  { a: "ANAGRAM", q: "What do you call a word made by rearranging another's letters?" },
  { a: "RHYME", q: "What do 'cat' and 'hat' do with each other?" },
  { a: "SYNONYM", q: "What is a word meaning the same as another called?" },
  { a: "ANTONYM", q: "What is a word meaning the opposite of another called?" },
  { a: "VOWEL", q: "What is A, E, I, O or U classified as?" },
  { a: "ALPHABET", q: "What is the full set of letters from A to Z called?" },
  { a: "RIDDLE", q: "What is a puzzling question with a clever answer called?" },
  { a: "PROVERB", q: "What is a short well-known saying offering advice called?" },
  { a: "HAIKU", q: "Which Japanese poem has three lines and seventeen syllables?" },
  { a: "VERB", q: "What is a word describing an action called?" },
  { a: "NOUN", q: "What is a word for a person, place or thing called?" },
  { a: "PREFIX", q: "What is a word part added to the start of a word called?" },
  { a: "SILENT", q: "What kind of letter is the 'k' in 'knife'?" },
  { a: "PLURAL", q: "What form of a word shows more than one?" },
  { a: "ZEBRA", q: "Which black-and-white striped animal lives on the African plains?" },
  { a: "PYTHON", q: "Which large snake squeezes its prey, and names a coding language?" },
  { a: "FALCON", q: "Which fast bird of prey can dive over 300 km/h?" },
  { a: "CORAL", q: "What living structure forms the Great Barrier Reef?" },
  { a: "TSUNAMI", q: "What is a giant wave caused by an undersea earthquake?" },
  { a: "MONSOON", q: "What seasonal heavy rain affects South Asia?" },
  { a: "MERCURY", q: "Which planet is closest to the Sun?" },
  { a: "VENUS", q: "Which planet is the hottest in the solar system?" },
  { a: "URANUS", q: "Which planet rotates on its side?" },
  { a: "ECHO", q: "What is a sound that bounces back to you called?" },
  { a: "MIRAGE", q: "What optical illusion appears in the desert heat?" },
];
